### ISSUE TITLE
Runtime Error after an epoch

### ISSUE THREAD

**Issue by hhhThomas** [eeric/Face_recognition_cnn#3]
Thank you for your script that I have successfully started training mobilefacenet on a single Gpu with your script. However, after an epoch, I got the following error while testing verification:

--------------------------------------------------------------------------------------------------------------------------------------------
testing verification..
Traceback (most recent call last):
  File "train_one_gpu.py", line 146, in <module>
    main(parser.parse_args())
  File "train_one_gpu.py", line 134, in main
    callback_verification(global_step, backbone)
  File "C:\Users\hhhth\Desktop\Face Recognition\insightface\recognition\arcface_torch\utils\utils_callbacks.py", line 47, in __call__
    self.ver_test(backbone, num_update)
  File "C:\Users\hhhth\Desktop\Face Recognition\insightface\recognition\arcface_torch\utils\utils_callbacks.py", line 27, in ver_test
    self.ver_list[i], backbone, 10, 10)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\hhhth\Desktop\Face Recognition\insightface\recognition\arcface_torch\eval\verification.py", line 243, in test
    net_out: torch.Tensor = backbone(img)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\hhhth\Desktop\Face Recognition\insightface\recognition\arcface_torch\backbones\mobilefacenet.py", line 123, in forward
    x = self.layers(x)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\hhhth\Desktop\Face Recognition\insightface\recognition\arcface_torch\backbones\mobilefacenet.py", line 26, in forward
    return self.layers(x)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\hhhth\.conda\envs\fr\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
--------------------------------------------------------------------------------------------------------------------------------------------I I have tried different settings, while both fp16=True and fp16=False lead to the "Input type and weight type should be the same" error. I also tried pytorch 1.6.0 and pytorch 1.9.0 on both Windows and Linux environments, but the problem remained. 

Do you know how to solve this? Or could you let me know your working environment and packages versions?
Thank you very much!

**Comment by eeric** [comment]
line 243 in insightface/recognition/arcface_torch/eval/verification.py, modified as following: 
    net_out: torch.Tensor = backbone(img.cuda())

good luck!
don't forget get a star, thanks!

**Comment by eeric** [comment]
> line 243 in insightface/recognition/arcface_torch/eval/verification.py, modified as following:
> net_out: torch.Tensor = backbone(img.cuda())
> 
> good luck!

don't forget give a star, thanks!

**Comment by hhhThomas** [comment]
Hi @eeric,

thanks a lot. It works!
